In [1]:
a=1
b=7
c=a+b
print(c)

8


In [3]:
def my_funct():
    print("Hello")


In [4]:
my_funct()

Hello


In [5]:
def add(a,b):
    print(a+b)

In [6]:
add(1,7)

8


In [12]:
def ad(a,b):
   c=a+b
   print(c)

In [13]:
ad(1,7)

8


In [14]:
a=[1,2,3,4,5,6,7]
print(a)

[1, 2, 3, 4, 5, 6, 7]


In [15]:
text="Hello world hy"

In [16]:
text.split()

['Hello', 'world', 'hy']

In [17]:
text.split(" . ")

['Hello world hy']

In [18]:
te="H,llo,hy"

In [19]:
te.split(",")

['H', 'llo', 'hy']

In [20]:
a=text.split()

In [21]:
a[0]

'Hello'

In [22]:
a[1]

'world'

In [23]:
a[2]

'hy'

In [24]:
a=[1,2,3,4,5]
for i in a:
    print(i)

1
2
3
4
5


In [25]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [29]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [32]:
list1=[]
t=int(input("Enter the size  of the array"))
for i in range(0,t):
    l=input("Enter the values:")
    list1.append(l)
print(list1)

Enter the size  of the array3
Enter the values:1
Enter the values:2
Enter the values:3
['1', '2', '3']


In [1]:
import math
r=2
area=math.pi*r*r
print(area)

12.566370614359172


In [6]:
from package import pack
pack.sum(2,4)

6


In [5]:
import numpy as np

In [36]:
a=np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [8]:
z=np.zeros((2,3))

In [9]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
r=np.arange(0,10,5)

In [17]:
r

array([0, 5])

In [37]:
b=np.array([3,6,5])

In [19]:
a+b

array([4, 8, 8])

In [20]:
np.mean(a)

2.0

In [21]:
np.max(a)

3

In [30]:
c=np.array([[1,2],[3,4]])

In [31]:
c

array([[1, 2],
       [3, 4]])

In [32]:
d=np.array([[1,4],[3,5]])
d

array([[1, 4],
       [3, 5]])

In [33]:
c+d

array([[2, 6],
       [6, 9]])

In [34]:
c*d

array([[ 1,  8],
       [ 9, 20]])

In [38]:
a*b


array([ 3, 12, 15])

In [39]:
e=c*d
e

array([[ 1,  8],
       [ 9, 20]])

In [41]:
f=np.dot(c,d)
f

array([[ 7, 14],
       [15, 32]])

In [42]:
c

array([[1, 2],
       [3, 4]])

In [43]:
d

array([[1, 4],
       [3, 5]])

In [44]:
f

array([[ 7, 14],
       [15, 32]])

In [45]:
f.T

array([[ 7, 15],
       [14, 32]])

In [46]:
print("\n Matrix 1:\n",c)
print("\n Matrix 2 :\n",d)
print("\n Addition :\n",c+d)
print("\n Subtraction :\n",c-d)
print("\n Multiplication(Element wise) :\n",c*d)
print("\n Dot Multiplication(row * rolumn) :\n",f)
print("\n Transpose :\n",f.T)


 Matrix 1:
 [[1 2]
 [3 4]]

 Matrix 2 :
 [[1 4]
 [3 5]]

 Addition :
 [[2 6]
 [6 9]]

 Subtraction :
 [[ 0 -2]
 [ 0 -1]]

 Multiplication(Element wise) :
 [[ 1  8]
 [ 9 20]]

 Dot Multiplication(row * rolumn) :
 [[ 7 14]
 [15 32]]

 Transpose :
 [[ 7 15]
 [14 32]]
