In [ ]:
AIM:- NAIVE BAYES ALGORITHM 
    Question 1:- Program to implement Naïve Bayes algorithm using any standard 
    dataset available in the public domain and find the accuracy of the 
    algorithm.

In [1]:
# AIM: Naïve Bayes Algorithm on Iris Dataset

import numpy as np 
from sklearn import datasets 
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score 

# Load the Iris dataset 
iris = datasets.load_iris() 
X = iris.data 
y = iris.target 

# Split the data into training and testing sets (80% training, 20% testing) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

# Create a Gaussian Naive Bayes classifier 
nb_classifier = GaussianNB() 

# Train the classifier using the training data 
nb_classifier.fit(X_train, y_train) 

# Make predictions on the testing data 
y_pred = nb_classifier.predict(X_test) 

# Calculate the accuracy of the classifier 
accuracy = accuracy_score(y_test, y_pred) 
print(f"Accuracy: {accuracy * 100:.2f}%") 

# Predict on a new sample 
new_sample = np.array([[5.1, 3.5, 1.4, 0.2]])  # Example flower

print("New sample shape:", new_sample.shape)
print("Model expects:", nb_classifier.n_features_in_, "features")

prediction = nb_classifier.predict(new_sample)
print("Prediction:", prediction)
print("Predicted class:", iris.target_names[prediction[0]])

Accuracy: 100.00%
New sample shape: (1, 4)
Model expects: 4 features
Prediction: [0]
Predicted class: setosa


In [4]:
#naive bayes
import numpy as np
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

#load the iris dataset

iris=datasets.load_iris()
X=iris.data
y=iris.target
#split the data into training and testing sets(80% training,20% testing)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#create a Gaussian Naive Bayes classifier
nb_classifier=GaussianNB()

#Train the classifier using the train data
nb_classifier.fit(X_train,y_train)

#make predictions on the testing data
y_pred=nb_classifier.predict(X_test)

#consusion matrix
res=confusion_matrix(y_test,y_pred)
print("confusion_matrix \n",res)

#classification report
res1=classification_report(y_test,y_pred)
print("Classification_report \n",res1)

#calculate the accuracy of the classifier
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:\n",accuracy)
# print(f"Accuracy: {accuracy*100:.2f}%")

confusion_matrix 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification_report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy:
 1.0


In [7]:
import numpy as np
import pandas as pd
# from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('food.csv')

X = data.iloc[:, :3]
# print(X)
y= data.iloc[:, 3]

le = LabelEncoder()
categorical_columns = ['Ingredient']
for col in categorical_columns:
   X[col] = le.fit_transform(X[col])
   y = le.fit_transform(y)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

knn = GaussianNB()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

sample=[[1,10,9]]
k=knn.predict(sample)
print(k)

accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

[0]
1.0
